---
functional:
  - Сервис должен позволять пользователям пройти пробную игру без регистрации и авторизации на сайте. Пробная игра должна генерироваться автоматически (без выбора задачи, уровня ее сложности и времени для ее решения), противником должен выступать только бот
  - Сервис должен позволять пользователям регистрироваться на сайте 
    - через заполнение полей для ввода псевдонима пользователя, его электронной почты и пароля
    - через учетную запись на GitHub
    - через учетную запись на Discord
  - Сервис должен позволять пользователям авторизовываться на сайте 
    - через заполнение полей для ввода электронной почты пользователя и пароля
    - через учетную запись на GitHub
    - через учетную запись на Discord
  - Форма регистрации через заполнение полей для ввода должна соответствовать следующим требованиям 
    - Псевдоним пользователя должен содержать от 3 до 16 символов, состоящих из латинских букв, цифр и подчеркивания. Начинаться только с латинской буквы
    - Пароль должен содержать от 6 до 16 символов, не должен содержать пустые символы
    - Электронная почта должна быть валидной
    - Форма должна содержать поле с подтверждением пароля
    - При неверном заполнении пользователем полей должны отображаться сообщения об ошибке
  - Форма аторизации пользователя должна содержать поля для ввода электронной почты и пароля
  - Авторизованный пользователь должен иметь возможность видеть на главной странице сайта список игр
  - Авторизованный пользователь должен иметь возможность решать алгоритмические задачи на скорость с другими игроками в реальном времени. В игре участвуют два игрока, которые видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - После авторизации в игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Авторизованному пользователю можно выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие зарегистрированные пользователи могут следить за ходом игры
  - Сервис должен содержать общий чат для всех зарегистиррованных пользователей
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи для зарегистрированных пользователей. Редактор для ввода кода выглядит как проигрыватель
  - Зарегитсрированные пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть с открытым исходным кодом
implicit:
  - Сайт должен содержать ссылку на исходный код на GitHub
  - Сайт должен содержать ссылку на текущую версию сайта
  - Сайт должен позволять устанавливать зарегитсрированному пользователю основной язык программирования, который устанавливается в игре по умолчанию
  - Сайт должен позволять авторизованному пользователю выйти из своего профиля
